In [3]:
from ultronlib.dataproviders import CSVProvider
data = CSVProvider("./inputs/test.csv")

display(data.df)

,ticker,date,open,high,low,close,volume,closeadj,closeunadj,lastupdated
0,AAPL,2018-12-31,39.633,39.840,39.120,39.435,140013864.0,37.665,157.74,2024-11-08
1,AAPL,2018-12-28,39.375,39.630,38.638,39.057,169165696.0,37.304,156.23,2024-11-08
2,AAPL,2018-12-27,38.960,39.193,37.517,39.038,212468260.0,37.285,156.15,2024-11-08
3,AAPL,2018-12-26,37.075,39.307,36.680,39.292,234330176.0,37.528,157.17,2024-11-08
4,AAPL,2018-12-24,37.038,37.888,36.648,36.708,148676928.0,35.059,146.83,2024-11-08
...,...,...,...,...,...,...,...,...,...,...
77,AAPL,2018-09-10,55.237,55.462,54.117,54.583,158065812.0,51.950,218.33,2024-11-08
78,AAPL,2018-09-07,55.462,56.343,55.178,55.325,150479240.0,52.657,221.30,2024-11-08
79,AAPL,2018-09-06,56.557,56.837,55.325,55.775,137159904.0,53.085,223.10,2024-11-08
80,AAPL,2018-09-05,57.248,57.417,56.275,56.718,133331840.0,53.982,226.87,2024-11-08
81,AAPL,2018-09-04,57.102,57.295,56.657,57.090,109560528.0,54.337,228.36,2024-11-08